### ISSUE TITLE
Croc Room Tree Watering Point Max

### ISSUE THREAD

**Issue by Goblinaro** [AbusiveTuna/ToA_Points#4]
As far as I'm aware, the way that the croc watering works is that watering the tree solo gives 200 points, but if you are in a duo then one person watering the tree gives both players 100 points each. As far as the maximum goes, originally the plugin would keep going as high as possible, when in actuality croc succin doesn't actually bypass the 20k room point limit. 

I did see the modifications to the plugin that would reduce the point cap, but is the point maximum you can get from croc succin only 10k in a solo now? I thought it would be 20k for a solo, and 10k per person in a duo if i'm not mistaken, but trying a croc farm in a solo now my points wouldn't go above 10k when watering the tree, and although i could continue getting points from killing a croc, the points would reset back down to 10k once I watered the tree again.

**Comment by AbusiveTuna** [comment]
10k cap is in place to prevent boosting discords from misleading people about their services and purple chance.

**Comment by Goblinaro** [comment]
Right but that doesn't answer my question, does croc farming solo still give a single player 20k points and the 10k point cap is just because of how duos work and the points being split?
