### ISSUE TITLE
Question: Source For The Room Caps

### ISSUE THREAD

**Issue by jb1361** [AbusiveTuna/ToA_Points#5]
Iv been trying to find a source for the Room Point caps to answer these two questions.

1: Is the point cap per room actually 20,000?
2: Is the point cap per room raid wide or individual wide?

**Comment by AbusiveTuna** [comment]
https://secure.runescape.com/m=news/tombs-of-amascut-drop-mechanics--osmumtens-fang?oldschool=1

> You cannot gain more than 20,000 Room points as an individual in a single room.
> You cannot accumulate more than 64,000 Total points as an individual in the entire raid.

This is also backed up by the wiki calculator which had input from jmods when it was being created: https://oldschool.runescape.wiki/w/Module:Tombs_of_Amascut_loot

It won't have the cap on it, but it does show the "puzzle" rooms being treated the same as boss rooms in terms of point mechanics.
