### ISSUE TITLE
 1 > man Boosting service cap prohibits solo point boosting correct count

### ISSUE THREAD

**Issue by HunterHardwick** [AbusiveTuna/ToA_Points#6]
This code put in to protect someone getting boosted from scams prohibits solo water boosters from seeing their progress between 10k-20k points for boosting. This causes a solo booster to guess where their points are at before 20k and could cause them to stop short. Any chance you can disable this check on partysize of 1? 

https://github.com/AbusiveTuna/ToA_Points/blob/a0f1c04d5c5046fa0780cb38dc649b6a6b55a3da/src/main/java/com/tuna/toa/ToAPointsPlugin.java#L113

Appreciate the plugin by the way :)

**Comment by AbusiveTuna** [comment]
Oops, didn't see this for a while but fixed with 3d4bb736d24ced4b267878609819f5cfc96ddbd1. Going to do a quick test of it later today, then make the pull request for RL.
